### ISSUE TITLE
MacOS keyboard hotkeys for text selection doesn't work in plugin's Tree mode

### ISSUE THREAD

**Issue by originalrusyn** [paolosimone/virtual-json-viewer#36]
Hi,
Could you please make it possible to use MacOS keyboard hotkeys for text selection, such as:

```
Select text to beginning of a line – Shift+Command+Left Arrow
Select text to end of a line – Shift+Command+Right Arrow
Select text to beginning of current word – Shift+Option+Right Arrow
Select text to end of current word – Shift+Option+Right Arrow
Select text to beginning of all text – Shift+Command+Up Arrow
Select text to end of all text – Shift+Command+Down Arrow
```

( or introduce some new hotkeys for text selection, for example like https://www.jetbrains.com/go/guide/tips/expanding-shrinking-selection/ ) in virtual-json-viewer plugin's in Tree mode?

Because it's currently hard to copy text in that mode, for example UUIDs

**Comment by paolosimone** [comment]
Hi @originalrusyn, thanks again for choosing this plugin and for your feedback!

Unfortunately what you are proposing is not feasible because:
- in general the text is read-only so there isn't a cursor to move around like in IDEs
- in Tree mode in particular the text is dynamically fragmented across several html components (that's what makes it fast and easy to navigate)

But I agree that it would be nice to have a shortcut to quickly select a value such as a UUID in Tree mode, so in #37 I introduced:
- `shift + left arrow`: select node key
- `shift + right arrow`: select node value
- `command + a`: select whole line
    - this one is a bit buggy in chrome because it will add an extra newline when pasting to another editor

Expanding selection across multiple lines would not work as intended due to the complex DOM structure.

Hope you'll find it useful!

---

As an extra suggestion, in case you need to copy-paste several UUIDs you could leverage the JQ filtering and the Raw view.

Example: to copy all ids from a list of json objects

```json
[{"id": 1, "field": "value_1"}, {"id": 2, "field": "value_2"}]
```

1. `command + shift + f`: goto JQ filter
2. insert `map(.id)` and hit enter
3. `command + i`: switch to raw view
4. `command + 0`: focus text area
5. `command + a`: copy text
