### ISSUE TITLE
Unexpected non-whitespace character after JSON at position 7509

### ISSUE THREAD

**Issue by cmadsen** [paolosimone/virtual-json-viewer#38]
I get a "Unexpected non-whitespace character after JSON at position 7509" when trying to use jq filtering. If I use jq from the cmd line the filtering works fine. 

Is there a way to get more debug info about the JSON in question? 

The JSON does contain UTF like "GÖTEBORG" and "Højrup"

**Comment by paolosimone** [comment]
Hi @cmadsen, thanks for using my plugin!

The error you get is not from jq but from javascript's `JSON.parse`: jq command must return a valid json in order to be rendered by the plugin. Example here: https://github.com/paolosimone/virtual-json-viewer#why-this-valid-jq-command-doesnt-work

For sure I will include this constraint directly in the error message, since you are not the first one to be puzzled #22
