### ISSUE TITLE
Add setting to show searching result context in Tree mode

### ISSUE THREAD

**Issue by originalrusyn** [paolosimone/virtual-json-viewer#44]
I would like to see have some setting which allow me to see searching result context in Tree mode.
For example, let's say I need to search "Merry" text occurrences here https://api.github.com/users/paolosimone/repos
Current searching result:
<img width="358" alt="image" src="https://github.com/paolosimone/virtual-json-viewer/assets/4712828/86a2f2bd-170e-4230-8669-10c2176cb09f">
I would also like to see all other attributes of the json array element

**Comment by paolosimone** [comment]
Hi @originalrusyn , thanks as usual for your feedback!

It's a reasonable request, the solution I have in mind (#45) is allowing 3 search options:

Examples searching `"owner"` in  https://api.github.com/users/paolosimone/repos , notice the top-right eye icon

**Show all** *[new!]*

It always shows the whole json and highlights matches.  
*Warn:* since it doesn't filter anything you'll have to scroll down to find matches

![image](https://github.com/paolosimone/virtual-json-viewer/assets/11669196/bbf72160-abb2-4ab1-8879-65c05651fb22)



**Show subtree** *[default]*

It shows matches and their subtree. 

![image](https://github.com/paolosimone/virtual-json-viewer/assets/11669196/131d8a81-f8e0-4740-9f46-0ce7c30c6120)


**Show matches only**

Only shows exact matches.

![image](https://github.com/paolosimone/virtual-json-viewer/assets/11669196/d5aa35b8-0808-49ae-9784-f478bb0e80b0)

---

This feature will be available soon in v1.1.0. I will also try to add a setting to customize the default visibility mode, but it needs further investigation (see #46).

Don't forget to star the project on github! ⭐

**Comment by originalrusyn** [comment]
Hi @paolosimone 
Thank for your answer.

Just to double check
The "Show subtree" setting will show all properties of first element of json array for https://api.github.com/users/paolosimone/repos when I search "Merry" because the occurrence of the searching word is belong to the first element ( like on screenshot below )?
<img width="1122" alt="image" src="https://github.com/paolosimone/virtual-json-viewer/assets/4712828/8cf7437c-f720-4507-8826-60c50933185f">
If yes, that's what I want.
Thanks a lot.

**Comment by paolosimone** [comment]
> The "Show subtree" setting will show all properties of first element

nope, the "Show subtree" is the current version's default, so it will behave like your original post.

To do what you want you will have to switch to the new "Show all" mode that will:
- collapse and fade all array items without search occurrences
- expand items with search occurrences and keep its siblings

So searching "Merry" with "Show all" will output:

![image](https://github.com/paolosimone/virtual-json-viewer/assets/11669196/6316c3bd-c309-4449-9cfc-75ca73e43bef)

To give you another example with a match on array item which is not the first, searching "Navidad" will output:

![image](https://github.com/paolosimone/virtual-json-viewer/assets/11669196/9525d5b5-0c4d-4dd7-8337-e8679001282f)

**Comment by paolosimone** [comment]
As I side note, I confirm that you will be able to select the default search mode in settings

![image](https://github.com/paolosimone/virtual-json-viewer/assets/11669196/a2a889bb-b618-4a0e-a3b7-79371f4c8ec4)

**Comment by m-titov** [comment]
Ok,
Thnaks
