### ISSUE TITLE
Fall back to "raw" view when JQ output isn't parseable

### ISSUE THREAD

**Issue by nightpool** [paolosimone/virtual-json-viewer#51]
Now that the extension has a "raw" view fallback, I think https://github.com/paolosimone/virtual-json-viewer/issues/22 and #38 can be revisited. It's probably the most common issue users run into with this extension—writing a JQ query they expect to work and then being stymied by the limitations of the viewer. I know it happened to me within 5 minutes of installing it. 

Alternatively, at the very least, please add support for the "newline delimited JSON" formats which JQ outputs natively when you using the stream parsing helpers, like `[]`. In this case if JSON parsing fails, you can fall back to parsing each line itself as individual JSON content.

**Comment by nightpool** [comment]
In fact, since the current extension doesn't provide any way to pass flags like --raw or --csv, the "newline delimited JSON" format is the only possible output of JQ that should exist. So there's really no need to fall back to the raw format if you extend the virtual viewer to allow displaying multiple JSON objects sequentially

**Comment by paolosimone** [comment]
Hey @nightpool , thanks for your feedback!

> writing a JQ query they expect to work and then being stymied by the limitations of the viewer. I know it happened to me within 5 minutes of installing it

This is an extremely valid point! As you can imagine I wrote this extension mainly for personal usage and this limitation never bothered me, but you are right when you say it's frustrating for new users, so it 's about time to address it.

> Now that the extension has a "raw" view fallback...

Unfortunately we can't just show the output of a JQ command as-is, since "raw" view is not really "raw": it still needs a parsed JSON to function properly (pretty-print, expand/collapse, download...)

> So there's really no need to fall back to the raw format if you extend the virtual viewer to allow displaying multiple JSON objects sequentially

Bingo! I agree the cleanest solution is to add support for [JSON Lines](https://jsonlines.org/): see #53 

This issue will be closed after merging the related PR, the new feature will be included in the next release 🚀
